env:
  browser: true
  es6: true
  jest: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  $: readonly
  ClassicEditor: readonly
  initClassicEditor: readonly
parser: '@babel/eslint-parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
rules:
  arrow-parens:
    - error
    - always
  comma-dangle:
    - error
    - never
  complexity:
    - error
    - 11
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console:
    - error
    - allow:
      - warn
      - error
  no-unused-vars:
    - 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
