version: '3.7'

services:
  app:
    image: registry.communicatio.com/ikusei/smart-village-app-rss-importer
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
    configs:
      - source: smart-village-app-rss-importer-unicorn-rb
        target: /app/config/unicorn.rb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/assets
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx
    depends_on: [app]
    networks: [default, public]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - unicorn:/unicorn
      - assets:/public
    labels:
      - traefik.docker.network=public
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  unicorn:
  assets:
  settings:

configs:
  smart-village-app-rss-importer-nginx-conf:
    external: true
  smart-village-app-rss-importer-unicorn-rb:
    external: true

networks:
  public:
    external: true
